auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: lhan's Blog
url: http://HenryHK.github.io
feed: /atom.xml
author_info: <a href="http://henryhk.github.io">BieYuu</a>
